name: Change version setup
description: 'Action to change version setup'

runs:
  using: "composite"
  steps:
    - run: |
        version=$(grep -oP "(?<=version=\")[^\"]+" setup.py)
        IFS='.' read -r -a version_parts <<< "$version"
        new_version="${version_parts[0]}.$((${version_parts[1]} + 1)).${version_parts[2]}"
        sed -i "s/version=\"$version\"/version=\"$new_version\"/" setup.py
        git config user.email "actions@github.com"
        git config user.name "Github Actions"
        git tag $new_version
        git push origin $new_version
      shell: bash