name: Change version setup
description: 'Action to change version setup'

inputs:
  is_release_input:
    description: 'Check if it is release'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.is_release_input }}" == "true" ]]; then   
          version=$(grep -oP "(?<=version=\")[^\"]+" setup.py)
          IFS='.' read -r -a version_parts <<< "$version"
          new_version="${version_parts[0]}.$((${version_parts[1]} + 1)).${version_parts[2]}"
          sed -i "s/version=\"$version\"/version=\"$new_version\"/" setup.py
          git config user.email "actions@github.com"
          git config user.name "Github Actions"
          git add setup.py
          git commit -m "New Version: $new_version"
          git push origin HEAD:Dev
          git tag "v$new_version"
          git push origin "v$new_version"
        else
          echo "Not versioning"
        fi
      shell: bash