name: Change version setup
description: 'Action to change version setup'

runs:
  using: "composite"
  steps:
    - run: |
        sed -i "s/version=[\"'][0-9.]*[\"']/version='hola'/g" "$setup_py"
        git config user.email "actions@github.com"
        git config user.name "Github Actions"
        git add setup.py
        git commit -m "New Version: $new_version"
        git push origin HEAD:Dev
      shell: bash