name: Change version setup

on:
  workflow_dispatch:
    inputs:
      IS_RELEASE:
        description: 'Check if it is release'
        required: false
        type: boolean

jobs:
  ch_ver:
    name: Change version setup
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: Dev

    - name: Set Version
      uses: EloyGuillermo/ExerciseVersionSetup/change_version_action@Dev
      if: ${{ github.event.inputs.IS_RELEASE == 'true' }}
      with:
        is_release_input: ${{ github.event.inputs.IS_RELEASE }}