name: Change version setup

on: 
  workflow_dispatch:
    inputs:
        myInput:
          default: "my input value"
        myInput2:
          default: "my input value2"

jobs:
  ch_ver:
    name: Change version setup
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"

    - name: Set Version
      run: |
        version=$(grep -oP "(?<=version=\")[^\"]+" setup.py)
        IFS='.' read -r -a version_parts <<< "$version"
        ((version_parts[1]++))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        sed -i "s/version=\"$version\"/version=\"$new_version\"/" setup.py
        git config user.email "actions@github.com"
        git config user.name "Github Actions"
        git add setup.py
        git commit -m "New Version"
        git push origin main
