name: Change version setup

on:
  workflow_dispatch:
    inputs:
      IS_RELEASE:
        description: 'Check if it is release'
        required: false
        type: boolean

jobs:
  ch_ver:
    name: Change version setup
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Merge Dev to Main
      if: ${{ github.event.inputs.IS_RELEASE == 'true' }}
      id: merge
      run: |
        git config user.email "actions@github.com"
        git config user.name "Github Actions"
        git checkout main
        git merge -X theirs Dev
        git push origin main

    - name: Create Tag
      if: ${{ github.event.inputs.IS_RELEASE == 'true' }}
      run: |
        VERSION=$(grep -oP "(?<=version=\")[^\"]+" setup.py)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        git tag "v$VERSION"
        git push origin "v$VERSION"

    - name: Update version in Dev
      if: ${{ github.event.inputs.IS_RELEASE == 'true' }}
      env:
        VERSION: ${{ env.VERSION }}
      run: |
        IFS='.' read -r -a version_parts <<< "$VERSION"
        new_version="${version_parts[0]}.$((${version_parts[1]} + 1)).${version_parts[2]}"
        sed -i "s/version=\"$VERSION\"/version=\"$new_version\"/" setup.py
        git add .
        git commit -m "New Version: $new_version"
        git push