name: Change version setup

on: 
  push: 
    branches:
      - Dev

jobs:
  ch_ver:
    name: Change version setup
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: Dev

    - name: Set Version
      uses: EloyGuillermo/ExerciseVersionSetup/change_version_action@Dev