name: Change version setup

on: 
  workflow_dispatch:

jobs:
  ch_ver:
    name: Change version setup
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set Version
      run: |
        version=$(grep -oP "(?<=version=\")[^\"]+" setup.py)
        IFS='.' read -r -a version_parts <<< "$version"
        ((version_parts[1]++))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        sed -i "s/version=\"$version\"/version=\"$new_version\"/" setup.py
        git config --global user.email "eloy.g.marquez@gmail.com"
        git config --global user.name "EloyGuillermo"
        git add setup.py
        git commit -m "New Version"
        git push
